package net.gameoverse.soundtrack;

import com.google.gson.JsonArray;
import com.google.gson.JsonParser;
import net.fabricmc.api.ModInitializer;
import net.fabricmc.fabric.api.creativetab.v1.CreativeModeTabEvents;
import net.fabricmc.fabric.api.loot.v3.LootTableEvents;
import net.fabricmc.loader.api.FabricLoader;
import net.minecraft.core.Registry;
import net.minecraft.core.registries.BuiltInRegistries;
import net.minecraft.core.registries.Registries;
import net.minecraft.resources.Identifier;
import net.minecraft.resources.ResourceKey;
import net.minecraft.world.item.CreativeModeTabs;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.JukeboxSong;
import net.minecraft.world.level.storage.loot.LootPool;
import net.minecraft.world.level.storage.loot.entries.LootItem;
import net.minecraft.world.level.storage.loot.predicates.LootItemRandomChanceCondition;
import net.minecraft.world.level.storage.loot.providers.number.ConstantValue;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.List;

/**
 * Music discs by Soybean_56 (CC BY: credited by name with their YouTube channel, youtube.com/@soybean_56), from
 * Minecraft Infinite. Registers one disc per jukebox song in data/gameoverse_soundtrack/jukebox_song (generated by
 * tools/build.py, as is the disc list), puts them after the vanilla discs in the creative tab and gives every structure
 * chest a small chance to hold one. The audio is in the Gameoverse-Soundtrack resource pack.
 */
public final class Soundtrack implements ModInitializer {
    public static final String MOD_ID = "gameoverse_soundtrack";
    public static final Logger LOGGER = LoggerFactory.getLogger(MOD_ID);
    /** Chance per structure chest roll of one disc. */
    private static final float CHEST_CHANCE = 0.02F;
    private static final List<Item> DISCS = new ArrayList<>();

    @Override
    public void onInitialize() {
        for (String slug : discSlugs()) {
            Identifier id = Identifier.fromNamespaceAndPath(MOD_ID, "music_disc_" + slug);
            ResourceKey<Item> key = ResourceKey.create(Registries.ITEM, id);
            ResourceKey<JukeboxSong> song = ResourceKey.create(Registries.JUKEBOX_SONG, Identifier.fromNamespaceAndPath(MOD_ID, slug));
            Item item = new Item(new Item.Properties().setId(key).stacksTo(1).rarity(Rarity.RARE).jukeboxPlayable(song));
            DISCS.add(Registry.register(BuiltInRegistries.ITEM, id, item));
        }
        CreativeModeTabEvents.modifyOutputEvent(CreativeModeTabs.TOOLS_AND_UTILITIES).register(output -> DISCS.forEach(output::accept));
        LootTableEvents.MODIFY.register((key, builder, source, registries) -> {
            if (!key.identifier().getPath().startsWith("chests/")) {
                return;
            }
            LootPool.Builder pool = LootPool.lootPool()
                .setRolls(ConstantValue.exactly(1))
                .when(LootItemRandomChanceCondition.randomChance(CHEST_CHANCE));
            DISCS.forEach(disc -> pool.add(LootItem.lootTableItem(disc)));
            builder.withPool(pool);
        });
        LOGGER.info("Registered {} music discs by Soybean_56", DISCS.size());
    }

    private static List<String> discSlugs() {
        Path path = FabricLoader.getInstance().getModContainer(MOD_ID).orElseThrow()
            .findPath(MOD_ID + "/discs.json").orElseThrow();
        try {
            JsonArray array = JsonParser.parseString(Files.readString(path, StandardCharsets.UTF_8)).getAsJsonArray();
            List<String> out = new ArrayList<>();
            array.forEach(e -> out.add(e.getAsString()));
            return out;
        } catch (IOException e) {
            throw new IllegalStateException("Can't read the disc list", e);
        }
    }
}
